[global]
type=global

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0

[endpoint-1001]
type=endpoint
context=internal
disallow=all
allow=opus,ulaw
webrtc=yes
auth=auth-1001
aors=1001
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[auth-1001]
type=auth
auth_type=userpass
username=1001
password=${ENV(SIP_PASSWORD_1001)}

[1001]
type=aor
max_contacts=1
remove_existing=yes

[endpoint-1002]
type=endpoint
context=internal
disallow=all
allow=opus,ulaw
webrtc=yes
auth=auth-1002
aors=1002
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[auth-1002]
type=auth
auth_type=userpass
username=1002
password=${ENV(SIP_PASSWORD_1002)}

[1002]
type=aor
max_contacts=1
remove_existing=yes
