[global]
type=global
endpoint_identifier_order=username,auth_username

#include pjsip.runtime.conf

[transport-ws]
type=transport
protocol=ws
bind=0.0.0.0

[1001]
type=endpoint
context=internal
disallow=all
allow=opus,ulaw
webrtc=yes
auth=auth-1001
aors=1001
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1001]
type=aor
max_contacts=1
remove_existing=yes

[1002]
type=endpoint
context=internal
disallow=all
allow=opus,ulaw
webrtc=yes
auth=auth-1002
aors=1002
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1002]
type=aor
max_contacts=1
remove_existing=yes
